Added contact section
rugwizangoga/Portifolio pull request #3
Opened 2022-08-24 19:48 UTC by rugwizangoga

**Added contact section**

- added a contact form
- all contact fields are required
- when you submit it post the data to a formspree account

2022-08-24 20:24 UTC, ichala requested changes
Hi @rugwizangoga  , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Great Design ✅ 
- Correct workflow ✅ 
-  Form submission and validation are perfect ✅ 

 ## Required Changes ♻️

- [ ] kindly update your Readme file and add your friends that helped you in the author's section

- [ ] **_Check the comments below_**

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 20:24 UTC, ichala commented on index.html
> +                <textarea id="comment" class="names" rows="5" maxlength="500" name="message" required>Write your message here</textarea>
- [ ] kindly move the `Write your message here` inside a placeholder attribute because right now it's treated as a value of the text area

2022-08-24 20:24 UTC, ichala commented on style.css
> +}
- [ ]  kindly change the color `#b3bac5` its so light and barely visible, try something a bit darker

2022-08-25 07:56 UTC, sumairq approved these changes
### Hi Team , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 07:58 UTC, merged

2022-09-09 07:28 UTC, laiifuu commented on index.html
> +            </h2>
This H2 in the design is supposed to be centered. So please make sure you implement the appropriate changes.